interface ZIF_I_40_CONNECTIONTP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_40_CONNECTIONTP,
 CREATE_ZI_40_CONNECTIONTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DD66A2A33925611',
 DELETE_ZI_40_CONNECTIONTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DD66A2A3392D611',
 LOCK_ZI_40_CONNECTIONTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DD66A2A33919611',
 SAVE_ZI_40_CONNECTIONTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DD66A2A33935611',
 UNLOCK_ZI_40_CONNECTIONTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DD66A2A3391D611',
 UPDATE_ZI_40_CONNECTIONTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DD66A2A33929611',
 VALIDATE_ZI_40_CONNECTIONTP    TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DD66A2A33931611',
      END OF ZI_40_CONNECTIONTP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_40_CONNECTIONTP,
        BEGIN OF LOCK_ZI_40_CONNECTIONTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_40_CONNECTIONTP,
        BEGIN OF UNLOCK_ZI_40_CONNECTIONTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_40_CONNECTIONTP,
      END OF ZI_40_CONNECTIONTP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_40_CONNECTIONTP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056044E851EDB9DD66A2A33943611',
      END OF ZI_40_CONNECTIONTP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_40_CONNECTIONTP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DD66A2A33917611',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DD66A2A33913611',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DD66A2A33923611',
      END OF ZI_40_CONNECTIONTP,
      BEGIN OF ZI_40_CONNECTIONTP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DD66A2A3393B611',
      END OF ZI_40_CONNECTIONTP_LOCK,
      BEGIN OF ZI_40_CONNECTIONTP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DD66A2A33939611',
      END OF ZI_40_CONNECTIONTP_MESSAGE,
      BEGIN OF ZI_40_CONNECTIONTP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DD66A2A3393D611',
      END OF ZI_40_CONNECTIONTP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_40_CONNECTIONTP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_40_CONNECTIONTP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EDB9DD66A2A33909611' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_40_CONNECTIONTP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_40_CONNECTIONTP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056044E851EDB9DD66A2A33945611',
      END OF ZI_40_CONNECTIONTP,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_40_CONNECTIONTP             TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDB9DD66A2A3390D611',
 ZI_40_CONNECTIONTP_LOCK        TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDB9DD66A2A33915611',
 ZI_40_CONNECTIONTP_MESSAGE     TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDB9DD66A2A33911611',
 ZI_40_CONNECTIONTP_PROPERTY    TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDB9DD66A2A33921611',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_40_CONNECTIONTP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRIERID                      TYPE STRING VALUE 'CARRIERID',
  CONNECTIONID                   TYPE STRING VALUE 'CONNECTIONID',
  DEPARTURECOUNTRY               TYPE STRING VALUE 'DEPARTURECOUNTRY',
  DEPARTURECITY                  TYPE STRING VALUE 'DEPARTURECITY',
  DEPARTUREAIRPORT               TYPE STRING VALUE 'DEPARTUREAIRPORT',
  ARRIVALCOUNTRY                 TYPE STRING VALUE 'ARRIVALCOUNTRY',
  ARRIVALCITY                    TYPE STRING VALUE 'ARRIVALCITY',
  ARRIVALAIRPORT                 TYPE STRING VALUE 'ARRIVALAIRPORT',
  FLIGHTTIME                     TYPE STRING VALUE 'FLIGHTTIME',
  DEPARTURETIME                  TYPE STRING VALUE 'DEPARTURETIME',
  ARRIVALTIME                    TYPE STRING VALUE 'ARRIVALTIME',
  DISTANCE                       TYPE STRING VALUE 'DISTANCE',
  DISTANCEUNIT                   TYPE STRING VALUE 'DISTANCEUNIT',
  FLIGHTTYPE                     TYPE STRING VALUE 'FLIGHTTYPE',
  PERIOD                         TYPE STRING VALUE 'PERIOD',
      END OF ZI_40_CONNECTIONTP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_40_CONNECTIONTP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EDB9DD66A2A3390F611',
      END OF ZI_40_CONNECTIONTP,
    END OF SC_NODE_CATEGORY .
endinterface.
