interface ZIF_I_40_TRAVELTP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_40_TRAVELTP,
 CREATE_ZI_40_TRAVELTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DE8B290440AE1E2',
 DELETE_ZI_40_TRAVELTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DE8B290440B61E2',
 LOCK_ZI_40_TRAVELTP            TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DE8B290440A21E2',
 SAVE_ZI_40_TRAVELTP            TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DE8B290440BE1E2',
 UNLOCK_ZI_40_TRAVELTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DE8B290440A61E2',
 UPDATE_ZI_40_TRAVELTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DE8B290440B21E2',
 VALIDATE_ZI_40_TRAVELTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB9DE8B290440BA1E2',
      END OF ZI_40_TRAVELTP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_40_TRAVELTP,
        BEGIN OF LOCK_ZI_40_TRAVELTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_40_TRAVELTP,
        BEGIN OF UNLOCK_ZI_40_TRAVELTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_40_TRAVELTP,
      END OF ZI_40_TRAVELTP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_40_TRAVELTP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056044E851EDB9DE8B290440CC1E2',
      END OF ZI_40_TRAVELTP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_40_TRAVELTP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DE8B290440A01E2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DE8B2904409C1E2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DE8B290440AC1E2',
      END OF ZI_40_TRAVELTP,
      BEGIN OF ZI_40_TRAVELTP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DE8B290440C41E2',
      END OF ZI_40_TRAVELTP_LOCK,
      BEGIN OF ZI_40_TRAVELTP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DE8B290440C21E2',
      END OF ZI_40_TRAVELTP_MESSAGE,
      BEGIN OF ZI_40_TRAVELTP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDB9DE8B290440C61E2',
      END OF ZI_40_TRAVELTP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_40_TRAVELTP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_40_TRAVELTP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EDB9DE8B290440921E2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_40_TRAVELTP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_40_TRAVELTP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056044E851EDB9DE8B290440CE1E2',
      END OF ZI_40_TRAVELTP,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_40_TRAVELTP                 TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDB9DE8B290440961E2',
 ZI_40_TRAVELTP_LOCK            TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDB9DE8B2904409E1E2',
 ZI_40_TRAVELTP_MESSAGE         TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDB9DE8B2904409A1E2',
 ZI_40_TRAVELTP_PROPERTY        TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDB9DE8B290440AA1E2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_40_TRAVELTP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  TRAVELAGENCY                   TYPE STRING VALUE 'TRAVELAGENCY',
  TRAVELNUMBER                   TYPE STRING VALUE 'TRAVELNUMBER',
  TRAVELDESCRIPTION              TYPE STRING VALUE 'TRAVELDESCRIPTION',
  CUSTOMER                       TYPE STRING VALUE 'CUSTOMER',
  STARTDATE                      TYPE STRING VALUE 'STARTDATE',
  ENDDATE                        TYPE STRING VALUE 'ENDDATE',
  STATUS                         TYPE STRING VALUE 'STATUS',
  CHANGEDAT                      TYPE STRING VALUE 'CHANGEDAT',
  CHANGEDBY                      TYPE STRING VALUE 'CHANGEDBY',
      END OF ZI_40_TRAVELTP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_40_TRAVELTP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EDB9DE8B290440981E2',
      END OF ZI_40_TRAVELTP,
    END OF SC_NODE_CATEGORY .
endinterface.
